name: Feature Request
description: Suggest a new feature or improvement for MomShell
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve MomShell! Please describe your feature request below.

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which part of MomShell would this feature affect?
      options:
        - Soulful Companion (Chat)
        - Recovery Coach (Exercise/Pose Detection)
        - Community (Q&A/Posts)
        - Frontend/UI
        - Backend/API
        - New Component
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear description of what the problem is. e.g., I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: A clear description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: user-type
    attributes:
      label: User Perspective
      description: From which user's perspective is this feature requested?
      options:
        - New Mother (Postpartum)
        - Healthcare Professional
        - Family Member / Partner
        - Developer / Contributor
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
