"""Safety monitoring module for exercise sessions.

This module monitors for potentially dangerous situations and
triggers rest prompts when needed.
"""

import time
from collections import deque
from dataclasses import dataclass, field
from enum import Enum

from app.core.config import get_settings
from app.schemas.pose import PoseAnalysisResult, PoseData

settings = get_settings()


class SafetyAlertLevel(str, Enum):
    """Safety alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class SafetyAlert:
    """A safety alert generated by the monitor."""

    level: SafetyAlertLevel
    message: str
    recommendation: str
    timestamp: float = field(default_factory=time.time)


@dataclass
class SafetyStatus:
    """Current safety status of the session."""

    is_safe: bool = True
    should_rest: bool = False
    alerts: list[SafetyAlert] = field(default_factory=list)
    consecutive_poor_form: int = 0
    session_duration: float = 0.0
    time_since_last_rest: float = 0.0


class SafetyMonitor:
    """Monitors exercise safety and triggers appropriate alerts."""

    def __init__(
        self,
        max_consecutive_poor_form: int = 5,
        min_form_score: float = 40.0,
        rest_interval: int | None = None,
        fatigue_threshold: float | None = None,
    ) -> None:
        """Initialize the safety monitor.

        Args:
            max_consecutive_poor_form: Max frames of poor form before alert.
            min_form_score: Minimum acceptable form score.
            rest_interval: Seconds between rest prompts.
            fatigue_threshold: Threshold for fatigue detection (0-1).
        """
        self.max_consecutive_poor_form = max_consecutive_poor_form
        self.min_form_score = min_form_score
        self.rest_interval = rest_interval or settings.rest_prompt_interval
        self.fatigue_threshold = (
            fatigue_threshold or settings.fatigue_detection_threshold
        )

        # Internal state
        self._session_start: float | None = None
        self._last_rest_time: float | None = None
        self._consecutive_poor_form = 0
        self._score_history: deque[float] = deque(maxlen=30)  # Last 30 frames
        self._movement_history: deque[float] = deque(maxlen=60)  # Movement speed

    def start_session(self) -> None:
        """Start a new monitoring session."""
        self._session_start = time.time()
        self._last_rest_time = time.time()
        self._consecutive_poor_form = 0
        self._score_history.clear()
        self._movement_history.clear()

    def check(
        self,
        pose: PoseData,
        analysis: PoseAnalysisResult,
    ) -> SafetyStatus:
        """Check current pose and analysis for safety issues.

        Args:
            pose: Current pose data.
            analysis: Current analysis result.

        Returns:
            Current safety status with any alerts.
        """
        if self._session_start is None:
            self.start_session()

        current_time = time.time()
        alerts: list[SafetyAlert] = []

        # Update score history
        self._score_history.append(analysis.score)

        # Check for consecutive poor form
        if analysis.score < self.min_form_score:
            self._consecutive_poor_form += 1
        else:
            self._consecutive_poor_form = 0

        # Generate alerts based on conditions
        should_rest = False

        # Poor form alert
        if self._consecutive_poor_form >= self.max_consecutive_poor_form:
            alerts.append(
                SafetyAlert(
                    level=SafetyAlertLevel.WARNING,
                    message="连续多次动作不标准",
                    recommendation="请暂停一下，调整姿势后再继续",
                )
            )
            should_rest = True

        # Timed rest prompt
        time_since_rest = current_time - (self._last_rest_time or current_time)
        if time_since_rest >= self.rest_interval:
            alerts.append(
                SafetyAlert(
                    level=SafetyAlertLevel.INFO,
                    message=f"已连续训练{int(time_since_rest / 60)}分钟",
                    recommendation="建议稍作休息，喝点水",
                )
            )

        # Declining performance alert (fatigue indicator)
        if len(self._score_history) >= 20:
            recent_avg = sum(list(self._score_history)[-10:]) / 10
            earlier_avg = sum(list(self._score_history)[:10]) / 10
            if earlier_avg > 0 and recent_avg / earlier_avg < self.fatigue_threshold:
                alerts.append(
                    SafetyAlert(
                        level=SafetyAlertLevel.WARNING,
                        message="检测到动作质量下降",
                        recommendation="你可能有些疲劳了，建议休息一下再继续",
                    )
                )
                should_rest = True

        # Critical alerts from analysis
        critical_deviations = [
            d
            for d in analysis.deviations
            if any(keyword in d for keyword in ["严重", "危险", "过度", "疼痛"])
        ]
        if critical_deviations:
            alerts.append(
                SafetyAlert(
                    level=SafetyAlertLevel.CRITICAL,
                    message="检测到可能造成损伤的动作",
                    recommendation="请立即停止，检查动作是否正确",
                )
            )
            should_rest = True

        # Build status
        session_duration = current_time - (self._session_start or current_time)

        return SafetyStatus(
            is_safe=len([a for a in alerts if a.level == SafetyAlertLevel.CRITICAL])
            == 0,
            should_rest=should_rest,
            alerts=alerts,
            consecutive_poor_form=self._consecutive_poor_form,
            session_duration=session_duration,
            time_since_last_rest=time_since_rest,
        )

    def record_rest(self) -> None:
        """Record that the user took a rest."""
        self._last_rest_time = time.time()
        self._consecutive_poor_form = 0
        self._score_history.clear()

    def get_session_stats(self) -> dict:
        """Get statistics for the current session.

        Returns:
            Dict with session statistics.
        """
        if not self._score_history:
            return {
                "average_score": 0.0,
                "min_score": 0.0,
                "max_score": 0.0,
                "frames_analyzed": 0,
                "session_duration": 0.0,
            }

        scores = list(self._score_history)
        session_duration = time.time() - (self._session_start or time.time())

        return {
            "average_score": sum(scores) / len(scores),
            "min_score": min(scores),
            "max_score": max(scores),
            "frames_analyzed": len(scores),
            "session_duration": session_duration,
        }


def create_safety_monitor(**kwargs) -> SafetyMonitor:
    """Factory function to create a SafetyMonitor."""
    return SafetyMonitor(**kwargs)
